name: Marhaba auth CI
on:
  push:
    branches: [ "main" ]
jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ../../api/
    env: 
      PORT: ${{ secrets.PORT }}
      DB_URI: ${{ secrets.DB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SERVICE_TRANSPORTER: ${{ secrets.SERVICE_TRANSPORTER }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: test api
        uses: actions/setup-node@v18
      - run: npm install
      - run: npm test
  test-fronend:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ../../frontend/
    steps:
    - uses: actions/checkout@v3
    - name: test frontend
      uses: actions/setup-node@v18
    - run: npm install
    - run: npm test
  # docker-build-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build api
  #   - run: docker build -t api-image ../../api/
  # docker-build-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build frontend
  #   - run: docker build -t frontend-image ../../frontend/
